### ISSUE TITLE
libnl1 has been removed from distribution repositories

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#1]
In trying to compile this suite on Ubuntu 16.04 I realized it's difficult to do so because libnl-1 is no longer available in Debian or Ubuntu repositories.  

https://tracker.debian.org/pkg/libnl
https://launchpad.net/ubuntu/+source/libnl

If at all possible for the next release, it would be better to only use libnl-3.

**Comment by superm1** [comment]
Furthermore this statement is present on the libnl page (http://www.infradead.org/~tgr/libnl/):

> Support for 1.1.x releases is limited, backports are only done upon request. Do not develop new applications based on libnl1 and consider porting your applications to libnl3

**Comment by ybernat** [comment]
We agree. This change is already planned for the next version, which will use libnl3 only.
Also, please note that the initial version here supports RedHat only. The next version will support more distros.

**Comment by michael-jamet** [comment]
Hi Mario,

This has been resolved with the last release.

**Comment by ybernat** [comment]
bc8fa2eef1271ace68b15aaad094db809cc963bf
