### ISSUE TITLE
Userspace thunderbolt stack uses deprecated "at_console" for D-Bus policy

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#10]
In preparing packaging for Debian and Ubuntu I noticed this error is reported.
```
dbus-policy-at-console etc/dbus-1/system.d/thunderbolt.conf <policy at_console="true"><allow send_destination="com.Intel.Thunderbolt1"/>
```

In a future version this should be adjusted.  More information:

> The package contains D-Bus policy configuration that uses the deprecated at_console condition to impose a different policy for users who are "logged in at the console" according to systemd-logind, ConsoleKit or similar APIs, such as:
> 
>       <policy context="default">
>         <deny send_destination="com.example.PowerManagementDaemon"/>
>       </policy>
>       <policy at_console="true">
>         <allow send_destination="com.example.PowerManagementDaemon"/>
>       </policy>
>     
> The maintainers of D-Bus recommend that services should allow or deny method calls according to broad categories that are not typically altered by the system administrator (usually either "all users", or only root and/or a specified system user). If finer-grained authorization is required, the service should accept the method call message, then call out to PolicyKit to decide whether to honor the request. PolicyKit can use system-administrator-configurable policies to make that decision, including distinguishing between users who are "at the console" and those who are not.
> 
> Refer to https://bugs.freedesktop.org/show_bug.cgi?id=39611 for details.
https://lintian.debian.org/tags/dbus-policy-at-console.html

**Comment by ybernat** [comment]
Using PolicyKit looks like the correct approach.
We’ll look into it for the next release.

**Comment by ybernat** [comment]
Not relevant now that we don't have daemon nor D-Bus interface anymore.
tbtadm still should use PolicyKit for better granularity of the permission handling for various actions but this is to be addressed in a later release.
