### ISSUE TITLE
Cant build daemon

### ISSUE THREAD

**Issue by ksfga** [intel/thunderbolt-software-user-space#12]
Hello, I'm unable to build daemon, I have tried on debian testing and then on supported ubuntu 16.04. But with the same results on both platforms. Output from debian follows:

$ cmake ../ThunderboltService/Linux -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found LibDBus-c++-1: /usr/include/dbus-c++-1  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Finding systemd and dbus
-- SYSTEMD_SERVICES_INSTALL_DIR: /lib/systemd/system
-- DBUS_SERVICES_INSTALL_DIR: /usr/share/dbus-1/system-services
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ksfga/src/thunderbolt-software-user-space-fwupdate/thunderbolt-daemon-build
ksfga@ksfga-xps:~/src/thunderbolt-software-user-space-fwupdate/thunderbolt-daemon-build$ make
Scanning dependencies of target lib
[  2%] Building CXX object CMakeFiles/lib.dir/src/ConnectionManager.cpp.o
[  5%] Building CXX object CMakeFiles/lib.dir/src/Controller.cpp.o
[  7%] Building CXX object CMakeFiles/lib.dir/src/DBusController.cpp.o
[ 10%] Building CXX object CMakeFiles/lib.dir/src/DBusControllers.cpp.o
[ 12%] Building CXX object CMakeFiles/lib.dir/src/GenlWrapper.cpp.o
[ 15%] Building CXX object CMakeFiles/lib.dir/src/LinuxControllerCommandSender.cpp.o
[ 17%] Building CXX object CMakeFiles/lib.dir/src/LinuxUtils.cpp.o
[ 20%] Building CXX object CMakeFiles/lib.dir/src/MessageFromFwEvent.cpp.o
[ 23%] Building CXX object CMakeFiles/lib.dir/src/MessageUtils.cpp.o
[ 25%] Building CXX object CMakeFiles/lib.dir/src/P2PDevice.cpp.o
[ 28%] Building CXX object CMakeFiles/lib.dir/src/Port.cpp.o
[ 30%] Building CXX object CMakeFiles/lib.dir/src/logger.cpp.o
[ 33%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/AutoFD.cpp.o
[ 35%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/ConnectionManagerBase.cpp.o
[ 38%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/ControllerCommandSenderBase.cpp.o
[ 41%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/ControllerDetails.cpp.o
[ 43%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/ControllerSettings.cpp.o
[ 46%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/DriverCommandResponseLock.cpp.o
[ 48%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/TbtWmiApproveP2P.cpp.o
[ 51%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/TbtWmiMailboxCommand.cpp.o
[ 53%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/TbtWmiMessageToFW.cpp.o
[ 56%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/UniqueID.cpp.o
[ 58%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/Utils.cpp.o
[ 61%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/CommonUtils/CountingSemaphore.cpp.o
[ 64%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/CommonUtils/ScopeGuard.cpp.o
[ 66%] Building CXX object CMakeFiles/lib.dir/home/ksfga/src/thunderbolt-software-user-space-fwupdate/ThunderboltService/Shared/src/XDomainProperties/Properties.cpp.o
[ 66%] Built target lib
Scanning dependencies of target thunderboltd
[ 69%] Building CXX object CMakeFiles/thunderboltd.dir/thunderbolt.cpp.o
[ 71%] Linking CXX executable bin/thunderboltd
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::register_netlink_callbacks()::{lambda(nl_msg*, void*)#1}::_FUN(nl_msg*, void*)':
GenlWrapper.cpp:(.text+0x411): undefined reference to `nlmsg_hdr'
GenlWrapper.cpp:(.text+0x47b): undefined reference to `nl_msg_dump'
GenlWrapper.cpp:(.text+0x494): undefined reference to `nlmsg_data'
GenlWrapper.cpp:(.text+0x49f): undefined reference to `genlmsg_data'
GenlWrapper.cpp:(.text+0x4bb): undefined reference to `genlmsg_validate'
GenlWrapper.cpp:(.text+0x50e): undefined reference to `genlmsg_parse'
GenlWrapper.cpp:(.text+0x5d9): undefined reference to `nla_data'
GenlWrapper.cpp:(.text+0x5e9): undefined reference to `nla_len'
GenlWrapper.cpp:(.text+0x64d): undefined reference to `nla_get_u32'
GenlWrapper.cpp:(.text+0x6ec): undefined reference to `nla_get_u16'
GenlWrapper.cpp:(.text+0x6fb): undefined reference to `nla_get_u8'
GenlWrapper.cpp:(.text+0x709): undefined reference to `nla_get_u8'
GenlWrapper.cpp:(.text+0x717): undefined reference to `nla_get_flag'
GenlWrapper.cpp:(.text+0x728): undefined reference to `nla_get_string'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::register_netlink_callbacks()':
GenlWrapper.cpp:(.text+0x99f): undefined reference to `nl_socket_modify_cb'
GenlWrapper.cpp:(.text+0x9c0): undefined reference to `nl_socket_modify_cb'
GenlWrapper.cpp:(.text+0x9e0): undefined reference to `nl_socket_modify_err_cb'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::cb_error_handler(sockaddr_nl*, nlmsgerr*)':
GenlWrapper.cpp:(.text+0xcb8): undefined reference to `nl_geterror'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::cb_valid(nl_msg*)':
GenlWrapper.cpp:(.text+0x10a1): undefined reference to `nlmsg_hdr'
GenlWrapper.cpp:(.text+0x110b): undefined reference to `nl_msg_dump'
GenlWrapper.cpp:(.text+0x1124): undefined reference to `nlmsg_data'
GenlWrapper.cpp:(.text+0x112f): undefined reference to `genlmsg_data'
GenlWrapper.cpp:(.text+0x114b): undefined reference to `genlmsg_validate'
GenlWrapper.cpp:(.text+0x119e): undefined reference to `genlmsg_parse'
GenlWrapper.cpp:(.text+0x1269): undefined reference to `nla_data'
GenlWrapper.cpp:(.text+0x1279): undefined reference to `nla_len'
GenlWrapper.cpp:(.text+0x12dd): undefined reference to `nla_get_u32'
GenlWrapper.cpp:(.text+0x137c): undefined reference to `nla_get_u16'
GenlWrapper.cpp:(.text+0x138b): undefined reference to `nla_get_u8'
GenlWrapper.cpp:(.text+0x1399): undefined reference to `nla_get_u8'
GenlWrapper.cpp:(.text+0x13a7): undefined reference to `nla_get_flag'
GenlWrapper.cpp:(.text+0x13b8): undefined reference to `nla_get_string'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::alloc_message(unsigned int, NHI_GENL_CMD)':
GenlWrapper.cpp:(.text+0x1642): undefined reference to `nlmsg_alloc'
GenlWrapper.cpp:(.text+0x1686): undefined reference to `genlmsg_put'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::send_message_async(unsigned int, NHI_GENL_CMD)':
GenlWrapper.cpp:(.text+0x1821): undefined reference to `nl_send_auto'
GenlWrapper.cpp:(.text+0x18da): undefined reference to `nl_msg_dump'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::~GenlWrapper()':
GenlWrapper.cpp:(.text+0x1a2d): undefined reference to `nl_socket_free'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::receive_thread()':
GenlWrapper.cpp:(.text+0x1b1d): undefined reference to `nl_recvmsgs_default'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::send_message_sync(nl_msg*)':
GenlWrapper.cpp:(.text+0x1c8e): undefined reference to `nl_send_auto'
GenlWrapper.cpp:(.text+0x1dc5): undefined reference to `nl_msg_dump'
GenlWrapper.cpp:(.text+0x1de7): undefined reference to `nl_geterror'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::GenlWrapper()':
GenlWrapper.cpp:(.text+0x2173): undefined reference to `nl_socket_alloc'
GenlWrapper.cpp:(.text+0x2188): undefined reference to `nl_socket_disable_seq_check'
GenlWrapper.cpp:(.text+0x2191): undefined reference to `genl_connect'
GenlWrapper.cpp:(.text+0x21a9): undefined reference to `genl_ctrl_resolve'
GenlWrapper.cpp:(.text+0x22e4): undefined reference to `nl_socket_free'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `GenlWrapper::send_message_sync(unsigned int, NHI_GENL_CMD, std::shared_ptr<ISerializable>)':
GenlWrapper.cpp:(.text+0x2b2e): undefined reference to `nla_put_u16'
GenlWrapper.cpp:(.text+0x2bd5): undefined reference to `nla_put_u32'
GenlWrapper.cpp:(.text+0x2bf4): undefined reference to `nla_put_flag'
GenlWrapper.cpp:(.text+0x2c24): undefined reference to `nla_put'
GenlWrapper.cpp:(.text+0x2c71): undefined reference to `nla_put_string'
GenlWrapper.cpp:(.text+0x2cae): undefined reference to `nla_put_u8'
CMakeFiles/lib.dir/src/GenlWrapper.cpp.o: In function `std::_Function_handler<void (nl_msg*), GenlWrapper::alloc_message(unsigned int, NHI_GENL_CMD)::{lambda(nl_msg*)#1}>::_M_invoke(std::_Any_data const&, nl_msg*&&)':
GenlWrapper.cpp:(.text+0x1ca): undefined reference to `nlmsg_free'
collect2: error: ld returned 1 exit status
CMakeFiles/thunderboltd.dir/build.make:147: recipe for target 'bin/thunderboltd' failed
make[2]: *** [bin/thunderboltd] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/thunderboltd.dir/all' failed
make[1]: *** [CMakeFiles/thunderboltd.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ybernat** [comment]
Just tried it on Debian testing and it compiled for me.
Are libnl-3-dev and libnl-genl-3-dev packages installed on your system?

**Comment by michael-jamet** [comment]
@ksfga  Did you get through?

**Comment by ksfga** [comment]
dpkg -l | grep libnl
ii  libnl-3-200:amd64                     3.2.27-1+b1                          amd64        library for dealing with netlink sockets
ii  libnl-3-dev:amd64                     3.2.27-1+b1                          amd64        development library and headers for libnl-3
ii  libnl-genl-3-200:amd64                3.2.27-1+b1                          amd64        library for dealing with netlink sockets - generic netlink
ii  libnl-genl-3-dev:amd64                3.2.27-1+b1                          amd64        development library and headers for libnl-genl-3
I have them both, I'm going to try it on clean system.

**Comment by ksfga** [comment]
On freshly installed system everything is okay... Thanks
