### ISSUE TITLE
Issues with Thunderbolt 3 MacBook Pro

### ISSUE THREAD

**Issue by zikphil** [intel/thunderbolt-software-user-space#15]
Hello,

I have the Kernel module and Daemon loaded on my Intel NUC. When i hook it up to my Mac Pro using the TB3->TB2 adapter, it's working fine, it's spinning up an ethernet device on Linux and i can see it on my Network Preferences on my mac. But when i hook it up to my Macbook Pro directly using TB3, absolutely nothing is happening. No Network Interface appears on Linux and nothing on mac.

Is this a compatibility issue?

Thanks,
Phil

**Comment by michael-jamet** [comment]
Hi Philippe,

You need to contact Apple support on this matter.

Best regards,

/Michael
