### ISSUE TITLE
Can't run Daemon with driver issue

### ISSUE THREAD

**Issue by jinhaotang** [intel/thunderbolt-software-user-space#17]
**Hi, I'm having an issue with the running of Daemon program on Ubuntu 16.04.2 in the Mac Mini Device(Dual Operating Systems). I have compiled the Kernel and compiled the Daemon program usccessfully. Everything works fine. But when I try to run the thunderboltd Daemon program. Errors occurred. Below is the output when I try to run thunderboltd:**

Info: Thunderbolt daemon version: 16.2.57.13-source      Thread: 140400540055744, func main line 139 (/home/surround1/Desktop/thunderbolt-software-user-space-fwupdate/ThunderboltService/Linux/thunderbolt.cpp)
Info: Thunderbolt module version: 17.1.63.1      Thread: 140400540055744, func main line 140 (/home/surround1/Desktop/thunderbolt-software-user-space-fwupdate/ThunderboltService/Linux/thunderbolt.cpp)
Info: Starting initialization      Thread: 140400540055744, func main line 141 (/home/surround1/Desktop/thunderbolt-software-user-space-fwupdate/ThunderboltService/Linux/thunderbolt.cpp)
Error: Error: can't extract family id, is driver installed and loaded?      Thread: 140400540055744, func GenlWrapper line 208 (/home/surround1/Desktop/thunderbolt-software-user-space-fwupdate/ThunderboltService/Linux/src/GenlWrapper.cpp)
Error: Error: Exception: can't extract family id, is driver installed and loaded?      Thread: 140400540055744, func main line 164 (/home/surround1/Desktop/thunderbolt-software-user-space-fwupdate/ThunderboltService/Linux/thunderbolt.cpp)

**It says that I don't have the driver installed. But in the compilation of kernels, I do have the configured these three drivers in the make menuconfig by checing the Thunderbolt Support, Apple Hardware support and Thunderbolt Networking to yes. I have also tried to set them to Dynamic Module output but still have this issue** .

**Whats confusing me is that: when I use**   _lspci -v_  **to check my thunderbolt connection, there only shows one thunderbolt driver in use. The thunderbolt_icm driver is now shown.**

06:00.0 System peripheral: Intel Corporation DSL5520 Thunderbolt [Falcon Ridge]
	Physical Slot: 0
	Flags: bus master, fast devsel, latency 0, IRQ 49
	Memory at a0900000 (32-bit, non-prefetchable) [size=256K]
	Memory at a0940000 (32-bit, non-prefetchable) [size=4K]
	Capabilities: [80] Power Management version 3
	Capabilities: [88] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [c0] Express Endpoint, MSI 00
	Capabilities: [a0] MSI-X: Enable- Count=16 Masked-
	Capabilities: [100] Device Serial Number c7-1f-78-11-f6-b3-02-00
	Capabilities: [200] Advanced Error Reporting
	Capabilities: [300] Virtual Channel
	Capabilities: [400] Power Budgeting <?>
	Capabilities: [500] Vendor Specific Information: ID=1234 Rev=1 Len=050 <?>
	Capabilities: [600] Latency Tolerance Reporting
	Kernel driver in use: thunderbolt

**I believe the thunderbolt_icm driver is the problem. But I do not know how to cope with it. I have tried** _modprobe thunderbolt_icm_. **But the driver just doesn't show up. Thank you so much for helping me out!**

**Comment by ybernat** [comment]
The thunderbolt_icm kernel module isn't targeted to Apple systems, due to some differences in how the FW is configured. This is why you see that 'thunderbolt' kernel module is in use for your Thunderbolt controller instead of 'thunderbolt_icm'.

The new kernel module accepted upstream (currently in linux-next tree) supports both PC and Apple systems. You may want to use it if what you are looking for is device approval and FW update.
P2P networking isn't available there yet.

**Comment by jinhaotang** [comment]
Hi, thanks for the update. This is really helpful!

Just one more thing: 

1. By referring to Apple systems, do you mean all the systems with in Apple devices(Maybe with a Linux or Ubuntu System in Apple devices) or you only mean the Mac OS?

Because here I am trying to use the P2P connection in the Ubuntu system in the Apple device,  I am wondering does the rule that P2P networking not being available also apply to this occasion?

2. If P2P networking in Ubuntu for apple systems don't work, could it work in Ubuntu on a non-apple system with the new kernels built and daemon program run? (The mother board in this non-apple system has no Thunderbolt port so I have to add a Thunderbolt Expansion card to it. My concern is that the Thunderbolt Expansion card  is said to only support Windows system. Could the driver in this kernel possibly support this expansion card in Linux? )

The Mother Board is ASUS Z97-A and the expansion card is ASUS ThunderboltEX II for your reference.

Thanks again for helping me with all this!

**Comment by ybernat** [comment]
1. Yes, I talked about cases like yours, where Linux is installed on Apple system. The difference comes from the way the FW in the Thunderbolt controller is configured.
2. For the ASUS setup you mentioned, you can use this module (not the new one from linux-next) for having P2P networking support.
However, please note that ASUS ThunderboltEX II is Thunderbolt 2 card and those cards may need FW upgrade before they can support P2P networking. I see that ASUS published such an update [1] but the FW update utility supports only Windows. As I see it, you can either try the card with this kernel module and daemon and see if it works, or start with using it with Windows for doing the FW update to be sure it includes the latest available FW version.

[1] https://www.asus.com/Motherboard-Accessory/ThunderboltEX_IIDUAL/HelpDesk_Download/

**Comment by jinhaotang** [comment]
Thank you so much for your timely response! This helps a lot!

Just to make sure, could the kernel module be the one from 
[(https://github.com/01org/thunderbolt-software-kernel-tree/tree/networking)](url)?

**Comment by ybernat** [comment]
Actually, it *must* be the one you linked to for P2P networking over Thunderbolt to work.

**Comment by jinhaotang** [comment]
Sorry, I don't quite get the term 'linked to'.  Say if I have a computer device system, I can build any system or kernels on the system if hardware permits. Can you give me some more detail on that?

**Comment by ybernat** [comment]
I'll rephrase my previous comment, as I admit it wasn't clear enough:
If you want the kernel to support P2P networking over Thunderbolt, you must use the kernel module from the link you brought before: https://github.com/01org/thunderbolt-software-kernel-tree/tree/networking

Does it make more sense now?

**Comment by jinhaotang** [comment]
Yeah. I see. The kernel [https://github.com/01org/thunderbolt-software-kernel-tree/tree/networking](url) is the only version that supports P2P networking.

Thanks a lot!
