### ISSUE TITLE
Missing "install" rule for CMake

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#21]
I notice it's up to me to try to guess where things go and I don't get anything with `make install`.  It would be good to be more prescriptive where to put things in that regard.

**Comment by ybernat** [comment]
Yeah, as the README says, this is currently missing, but I'll be happy to fix it.
Would you mind helping me here with an advice from the distros you know?

The natural place for `tbtadm` is under `/usr/bin` and I don't think there should be any issue with it, unless some distros prefer to put such things under `/usr/sbin`.

For the ACL handling, my default "Just Working(TM)" configuration is to put `tbtacl.rules` under `/lib/udev/rules/` and both `tbtacl` and `tbtacl-write` under `/lib/udev/`, but I'm not sure if this is the acceptable location for such things (and what numeric prefix the rules file is supposed to get).

**Comment by superm1** [comment]
I think `/usr/bin/` for `tbtadm `by default seems fine.  As for the numeric number for the udev rules to create it seems to me most projects are installing with `60-`.  Maybe just start with that and adjust later if necessary?  The order is most important for when there are potentially other rules that would trigger off one, which doesn't seem likely currently here.
