### ISSUE TITLE
libboost dependencies

### ISSUE THREAD

**Issue by finikorg** [intel/thunderbolt-software-user-space#31]
Would it make sense to remove libboost dependency and use standard C++ filesystem libs?

**Comment by ybernat** [comment]
I wish :)
Unfortunately, standard filesystem is only C++17.
(I thik it's better not to use the TS here, I remember there were some changes in between).

**Comment by ybernat** [comment]
(Also, I mentioned boost.ProgramOptions as a dependency as I think the command-line parsing should be moved to use it instead of the current ad-hoc approach.)

**Comment by westeri** [comment]
Boost brings quite lot of libraries so I think we may want to eventually go with standard posix filesystem APIs that exist in every Linux system :)

**Comment by ybernat** [comment]
I do prefer the standard one, but the availability is still not wide enough yet, I afraid.
Boost is widely used in general and we depend only on a specific part of it, so I'm not sure how much of an issue it is.

**Comment by ybernat** [comment]
Oh, you mentioned the standard POSIX interface.
The best that it has for traversing FS is `nftw`?
As long as the project uses C++, I think it makes sense to use a C++ API wherever possible, but this is just me.

**Comment by westeri** [comment]
We also have these functions such as opendir() and friends. Sure using C++ API makes sense if available but if we also have standard C APIs available as well I think we should use those if it avoids bringing megabytes of dependencies ;-)
