### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by GoPerry** [intel/thunderbolt-software-user-space#37]
I meet one build error showing the tbtacl-write lack of  RUNTIME DESTINATION for executable target.

Build OS:Ubuntu 17.10

-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
CMake Error at tbtacl/CMakeLists.txt:15 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "tbtacl-write".

CMake Error at tbtacl/CMakeLists.txt:17 (install):
  install PROGRAMS given no DESTINATION!

CMake Error at tbtxdomain/CMakeLists.txt:7 (install):
  install PROGRAMS given no DESTINATION!

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   program_options
-- Configuring incomplete, errors occurred!

**Comment by finikorg** [comment]
Do you have pkg-config?

**Comment by ybernat** [comment]
> Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

This is the issue.

**Comment by ybernat** [comment]
@yuzaipiaofei 
I'm closing this as I assume this solves the build error.

**Comment by GoPerry** [comment]
@finikorg  @ybernat  I change Host OS to Fedora26 to build successfully. 
Thanks .

**Comment by finikorg** [comment]
@yuzaipiaofei I use latest Ubuntu, works fine, also we have now CI using Ubuntu, you can check builds here:
https://travis-ci.org/01org/thunderbolt-software-user-space/builds/316552137?utm_source=github_status&utm_medium=notification

**Comment by ybernat** [comment]
Installing pkg-config should help, as mentioned (`sudo apt install pkg-config`)

**Comment by GoPerry** [comment]
Thanks all.
I suggest that you can update README to show supported OS for building.
Then add dependent packages for each OS.
I think it will help a bit for other guys.
