### ISSUE TITLE
Enumerating controllers won't start up thunderboltd or load thunderbolt-icm

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#4]
I've been experimenting with the December release, and found that using the tbtfwucli won't actually spin up it's dependencies.
```
$ tbtfwucli EnumControllers
error in /home/test/src/thunderbolt-software-user-space/fwupdate/tbtfwucli/tbtfwucli.cpp line 191: 0x1002 failed to communicate with service: Daemon communication failure while getting controller list: The name com.Intel.Thunderbolt1 was not provided by any .service files
```

If I manually modprobe `thunderbolt-icm` then thunderboltd starts up, but it doesn't actually enumerate still.
```
$ tbtfwucli EnumControllers
$
```

**Comment by ybernat** [comment]
When no TBT controller is present, neither the TBT kernel module nor the daemon is loaded.
When a controller comes up, both the kernel module and the daemon are loaded and the connection works.

As the controller has to be up for getting updated, there is no reason to bring the module up manually or by the tool.

**Comment by superm1** [comment]
Gotcha, OK will close this one as it's actually expected behavior with how TBT is working.
