### ISSUE TITLE
Error authorizing devices in security mode 0

### ISSUE THREAD

**Issue by finikorg** [intel/thunderbolt-software-user-space#44]
Found in automatic test:
Security level is only verified in approve-all. Calling approve <device> works not as expected for this security level.

**Comment by ybernat** [comment]
Isn't it printing `already authorized`?

**Comment by finikorg** [comment]
In my tests with emulated Thunderbolt I see that the tool tries to authorize, the real kernel should make devices "authorized".
I see that behaviour is different for approve-all and approve, should it be the same?

**Comment by ybernat** [comment]
It can be changed to be the same, but I don't sure there is a reason to do so.
`approve-all` tests it early so it will not have to do all the work of building the device map if it isn't relevant anyway.
Here, `approve` have to approve only this specific device and to test first if it's approved already. If it is, it doesn't matter the reason why it's approved, if it's because it's SL0 or because it was authorized earlier (by `tbtacl` or manually).

**Comment by finikorg** [comment]
BTW, can we have several domains? we have several functions doing similar work finding SL. findSL() finds security level of the first domain. Why approve-all does not use that function?

**Comment by ybernat** [comment]
Yes, on a host with multiple TBT controllers (e.g. Mac Pro, I think), each controller defines a domain.
To simplify the code there, `findSL()` uses the assumption that all domains are always in the same SL, but `approve-all` goes over all the domains anyway, so it can check each one directly.

**Comment by finikorg** [comment]
I think `approve-all` does the same as `findSL` since it returns.

**Comment by ybernat** [comment]
You are correct, of course. The real answer is that `findSL` was introduced later than `approve-all`, and I thought there is a difference in the behavior here so I didn't change `approve-all`. I'm still not sure if it worth changing, as `approve-all` traverse the whole subtree anyway. Do you still prefer to refactor it to use `findSL`? It can add to the consistency. It may be used to init `m_sl` in first place without doing so "manually" before each command that needs it.

**Comment by finikorg** [comment]
Fixed by PR #45

**Comment by ybernat** [comment]
(Next time, is better to add "Resolves #44" to the commit description, to get nicer linkage between those)
