### ISSUE TITLE
Controller enumeration doesn't work unless a thunderbolt device is connected

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#5]
This is likely related to issue #4.  I've found that the only time that enumeration works properly is when another thunderbolt device is connected to the host.  In my instance, I was using another PC over a C-C cable (and hence thunderbolt networking was activated).

[manually modprobe thunderbolt-icm]
```
$ tbtfwucli EnumControllers
```
[plug in tbt device]
```
$ tbtfwucli EnumControllers
08001575
```

**Comment by ybernat** [comment]
For power saving, TBT controller is powered off until something is connected.
Connecting a TBT device or another TBT computer is needed for bringing (and keeping) the controller up during the firmware upgrade process.

**Comment by superm1** [comment]
@ybernat thanks.  I am going to inquire with some other folks.  I understand Dell specifically has a GPIO that can pull the TBT controller up specifically for TBT FW flashing purposes directly at runtime.  

Assuming that is true and works, would you want some integration with libsmbios to do this on Dell systems in the thunderbolt library or would you rather see it happen in fwupd (which already has some libsmbios integration) when you land the fwupd provider?

**Comment by superm1** [comment]
I'm going to mark this closed as expected behavior.
When this gets integrated into the rest of the FW stack, i'll let the special wakeup for Dell systems land there.
