### ISSUE TITLE
device removal after tbtadm remove-all

### ISSUE THREAD

**Issue by nirmoy** [intel/thunderbolt-software-user-space#51]
does tbtadm remove-all should also remove the device completely.
I tried   tbtadm approve-all  --> gives me the eth0 over thunderbolt port 
             tbtadm remove-all --> eth0 still exist 

Is this normal?

**Comment by ybernat** [comment]
1. `remove` and `remove-all` are all about the ACL. A connected device can't be disconnected without a physical disconnection.
2. The network over TBT shouldn't be related to `approve`, the connection starts no matter if the devices in-between the two hosts are approved or not.

**Comment by nirmoy** [comment]
hi @ybernat Thanks for your clarification, can you please explain point 2 bit more.
As I understand I need to approve the device to use it if  the TBT is user/secure mode.

**Comment by ybernat** [comment]
I meant the host-to-host connection of TBT that creates a network over TBT.
If you are talking about a device that exposes a regular Ethernet port, my comment isn't relevant as you have to approve the device to use this port, as you correctly mentioned.

**Comment by nirmoy** [comment]
Okay thanks 👍 closing the issue!
