### ISSUE TITLE
When rpm package is uninstalled the ACL entries should be removed as well

### ISSUE THREAD

**Issue by westeri** [intel/thunderbolt-software-user-space#54]
Just noticed that when you remove the rpm package (generated by running `cpack -G RPM`) the ACL entries in `/var/lib/thunderbolt/acl` are left there. I think those should be removed as well if possible. In case of upgrade those should be left intact, though.

**Comment by ybernat** [comment]
I assume this is true for the DEB package too, as they are both auto-generated so they know only about the files they install, not about any config or data file added later.
I think the convention is to remove such data files not on a normal remove, just on `purge`. At least this is the convention with DEB packages.

I'm not sure how to make `cpack` to generate this without writing the `control` file or something like this manually.
I'm also not sure if this is needed. Seems like distros tend to build their own packages that follows their exact rules and conventions and not using our `cpack` mechanism anyway. So this is here mainly as a convenient tool for a user who wants to compile from source, and thus I wouldn't invest too much in it to this level. But this is just, like, my opinion. The decision is up to @finikorg, of course.

**Comment by westeri** [comment]
Yeah, just wanted to check with you if this is intended behavior or not. If you think it is not needed then we can close the issue.
