### ISSUE TITLE
Controller enumeration gets out of sync

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#6]
Probably related to the other issues (#4 and #5) that I filed, but just in case filing another.  I've found that what the library and tool provide from enumeration doesn't necessarily match what's actually on the system.

For example enumeration works when plugged into another TBT computer, but when that computer goes to sleep the enumeration still works but commands don't.

```
$ tbtfwucli EnumControllers
08001575
$ tbtfwucli GetVendorID 08001575
getVendorID failed: 0x102 Error while getting vendor ID: from src/thunderbolt-software-user-space/fwupdate/libtbtfwu/src/Controller.cpp:200: Error: 0x102 daemon reported an internal error. Details: Error while reading firmware: cb_error_handler: netlink error: Invalid address for specified address family
$ tbtfwucli ValidateFWImage 08001575 0x06E5.bin
Image validation failed: 0x102 Error while validating image: from src/thunderbolt-software-user-space/fwupdate/libtbtfwu/src/Controller.cpp:200: Error: 0x102 daemon reported an internal error. Details: Error while reading firmware: cb_error_handler: netlink error: Invalid address for specified address family
```

Waking up that other TBT device resolves the issue.
```$ tbtfwucli GetVendorID 08001575
0x00d4
$ tbtfwucli ValidateFWImage 08001575 0x06E5.bin
Image validation succeeded.

```

**Comment by michael-jamet** [comment]
Yes, we're aware of this caveat. You can see a mention in the daemon's README.
Since it's already on our radar, I would proceed in closing this issue to avoid duplicating.
