### ISSUE TITLE
(Cosmetic) tbtfwucli help description isn't accurate

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#7]
This is entirely cosmetic.

The usage help displays this:
```
usage: tbtfwucli EnumControllers
  or   tbtfwucli IsInSafeMode <controller>
  or   tbtfwucli ValidateFWImage <controller> <image_filename>
  or   tbtfwucli GetCurrentNVMVersion <controller>
  or   tbtfwucli GetVendorID <controller>
  or   tbtfwucli GetModelID <controller>
  or   tbtfwucli GetImageNVMVersion <image_filename>
  or   tbtfwucli FWUpdate <controller> <image_filename> [--no-prompt]

The <controller> argument must be one of the D-Bus controller
object names returned by the getControllerList call.  (The
controller's own notion of its ID can be retrieved with the
getControllerID call.)
```

In the bottom it refers to `getControllerList` and `getControllerID`, but those don't make sense in this context.  `<controller>` should really be one of the controllers that is output from `EnumControllers`.

**Comment by ybernat** [comment]
Thanks, Mario, good point. 
This is a left over from a previous version of the tool and will be removed on the next commit. 
Please note that this is just preliminary and it may include more similar cosmetic issues, as mentioned in the README, but we thought it would be terribly useful for users who want to quick start with the firmware update feature.

**Comment by superm1** [comment]
Yes, thanks for releasing it. It is already quite useful in it's current form.  I've been able to update NVM succesfully on a system today.

Something else that would be useful in this tool's commands:
1. would be a full summary command to show everything useful (enumerate everything, safe mode, VID/MID, NVM version)

**Comment by michael-jamet** [comment]
This has been addressed in last commit.
