### ISSUE TITLE
Missing man page

### ISSUE THREAD

**Issue by superm1** [intel/thunderbolt-software-user-space#9]
I was working out some details related to the packaging for Debian and Ubuntu around the userspace thunderbolt stack and noticed that a man page is missing for the command line flashing tool tbtfwucli.

In a future release, can you please include a man page?

Reference: https://lintian.debian.org/tags/binary-without-manpage.html

**Comment by ybernat** [comment]
We will add it for the next release.

We'd like to remind you that this tool was primarily intended to be used only as a sample.
At this time, packaging it for wide distribution looks less appropriate.

**Comment by superm1** [comment]
@ybernat OK.  Considering that I'll avoid packaging the tool until you indicate otherwise in a future release.  My main inclination for packaging it right now was to be able to cover the safe mode case, but at least for Dell systems we have a way to make that work w/ fwupd so it's not as important.

**Comment by ColinIanKing** [comment]
@superm1 do you have a plan of when you are going to package this tool, I was looking at attempting to package it up for Debian/Ubuntu but I see your ahead of me on that intention.

**Comment by superm1** [comment]
@ColinIanKing I started, but didn't get it all working yet.
https://github.com/dell/thunderbolt-software-user-space/tree/debian

Feel free to take that as a starting point if you want to finish before I do though :)

**Comment by superm1** [comment]
@ColinIanKing try now, let me know if that works for you.

**Comment by ColinIanKing** [comment]
On 01/09/17 20:45, Mario Limonciello wrote:
> @ColinIanKing <https://github.com/colinianking> try now, let me know if
> that works for you.

Thanks, I've got a copy and made some minor changes and will try and get
it uploaded to Debian by end of this week.

Much appreciated Mario!

Colin

**Comment by superm1** [comment]
@ColinIanKing great thanks.  Make sure you update it to the latest released version (should require changes for man pages and what goes in debian/install).
